# Generated by Django 2.0.6 on 2018-06-09 22:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predictor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ScikitMLPPredictor',
            fields=[
                ('predictor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='predictors.Predictor')),
                ('solver', models.CharField(choices=[(1, 'lbfgs')], max_length=32)),
                ('alpha', models.FloatField()),
                ('layers', models.CharField(max_length=512, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
            ],
            bases=('predictors.predictor',),
        ),
    ]
