# Generated by Django 2.0.6 on 2018-06-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scikitmlppredictor',
            name='solver',
            field=models.CharField(choices=[('lbfgs', 'lbfgs')], max_length=32),
        ),
    ]
