# Generated by Django 2.0.6 on 2018-06-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0002_auto_20180609_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='scikitmlppredictor',
            name='state_pickle',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
