# Generated by Django 2.0.6 on 2018-06-12 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0003_scikitmlppredictor_state_pickle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scikitmlppredictor',
            name='state_pickle',
        ),
    ]
