# Generated by Django 2.0.6 on 2018-06-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainjobs', '0002_trainjob_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainjob',
            name='state_pickle',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
